[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dnp3-module"
version = "0.1.0"
description = "DNP3 extension module"
authors = [{ name = "Kaden McCartney", email = "kmccartney7@gatech.edu" }]
requires-python = ">=3.13"
